sudo: required
branches:
    only:
    - master
    - develop
    - bugfix/tests
services:
    - docker
    - postgresql
dist: trusty
env:
    global:
    - POSTGRES_HOST:postgrsql
    - POSTGRES_USER= postgres
addons:
    - postgresql: "11.2"
before_install:
  - docker build -t lavinascoz/appbdb-test -f ./server/Dockerfile.dev ./server
script:
    - docker run -e CI=true lavinascoz/appbdb-test npm run test -- --coverage

after_success:
    - docker build -t lavinascoz/appbdb-server ./server
    - docker build -t lavinascoz/appdbd-client ./client

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push lavinascoz/appbdb-server
    - docker push lavinascoz/appbdb-client
