sudo: required
services:
    - docker
    - postgresql
dist: trusty
before_install:
    - docker build -t lavinascoz/appbdb-test -f ./server/Dockerfile ./server
    - psql -c 'create database postgres;' -U postgres
script:
    - docker run -e CI=true lavinascoz/appbdb-test npm run test -- --coverage

after_success:
    - docker build -t lavinascoz/appbdb-server ./server
    - docker build -t lavinascoz/appdbd-client ./client

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push lavinascoz/appbdb-server
    - docker push lavinascoz/appbdb-client
