sudo: required
services:
    - docker
    - postgresql
env:
    global:
    - POSTGRES_PASSWORD=

before_install:
    - docker build -t lavinascoz/appbdb-test -f ./server/Dockerfile ./server

script:
    - docker run -e CI=true lavinascoz/appbdb-test npm run test -- --coverage

after_success:
    - docker build -t lavinascoz/appbdb-server ./server

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push lavinascoz/appbdb-server