sudo: required
services:
    - docker
    - postgresql
dist: trusty
env:
    global:
    - POSTGRES_PASSWORD=
addons:
    - postgresql: "11.2"
before_install:
    - sudo apt-get update
    - sudo apt-get --yes remove postgresql\*
    - sudo apt-get install -y postgresql-11 postgresql-client-11
    - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
    - sudo service postgresql restart 11 
    - docker build -t lavinascoz/appbdb-test -f ./server/Dockerfile ./server

script:
    - bundle exec rake spec
    - docker run -e CI=true lavinascoz/appbdb-test npm run test -- --coverage

after_success:
    - docker build -t lavinascoz/appbdb-server ./server

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push lavinascoz/appbdb-server