sudo: required
services:
    - docker

before_install:
    - docker build -t lavinascoz/appBdB-test -f ./server/Dockerfile ./server

script:
    - docker run -e CI=true lavinascoz/appBdB-test npm run test -- --coverage

after_success:
    - docker build -t lavinascoz/appBdB-server ./server

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push lavinascoz/appBdB-server