version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432 
  api:
    build:
        dockerfile: Dockerfile
        context: ./server
    volumes:
        - ./server:/app
    depends_on:
      - postgres
    ports:
        - 3000:3000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432  
  tests:
    build:
        dockerfile: Dockerfile
        context: ./server
    volumes:
        - ./server:/app
    depends_on:
      - api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
    command: ["npm", "run", "test"]
    