version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=POSTGRES_HOST
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_PORT=5432 
  api:
    build:
        dockerfile: Dockerfile
        context: ./server
    depends_on:
      - postgres
    ports:
        - 5000:3000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432  
  tests:
    build:
        dockerfile: Dockerfile
        context: ./server
    depends_on:
      - api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
    command: ["npm", "run", "test"]
  client:
    build:
        dockerfile: Dockerfile
        context: ./client
    depends_on:
      - api
    ports:
        - 4000:3001
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432
    
