version: '3'
services:
  postgres:
    image: 'postgres:latest'
  api:
    build:
        dockerfile: Dockerfile
        context: ./server
    volumes:
        - /app/node_modules
        - ./server:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT=5432  
